general {
    grab_focus = true
}

cache {
    enabled = true
}

finders {
    default_finder = desktop
    desktop_prefix =
    unicode_prefix = .
    math_prefix = =
    font_prefix = '
    desktop_launch_prefix =
    desktop_icons = true
}

ui {
    window_size = 960 480
}
